import math
import pygame.font

from color import Color

# ---Constants---
# -Colors-
BASIC_COLORS = {
    "WHITE": Color(255, 255, 255),
    "BLACK": Color(0, 0, 0),
    "BLUE": Color(66, 135, 245)
}
# -Game-
INGAME_FPS = 5
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
UI_SCALE = math.ceil(SCREEN_WIDTH/SCREEN_HEIGHT)
NORMAL_FONT_SIZE = 18*UI_SCALE
FONT_SIZE = {
    "SMALL": NORMAL_FONT_SIZE//2,
    "NORMAL": NORMAL_FONT_SIZE,
    "MEDIUM": NORMAL_FONT_SIZE * 2,
    "BIG": NORMAL_FONT_SIZE * 3
}
SCREEN_BACKGROUND = BASIC_COLORS["BLUE"]
CELL_WIDTH = 8
CELL_HEIGHT = 8
CELL_DEFAULT_COLOR = BASIC_COLORS["BLUE"]
N_CELLS_HORIZONTAL = math.ceil(SCREEN_WIDTH / CELL_WIDTH)
N_CELLS_VERTICAL = math.ceil(SCREEN_HEIGHT / CELL_HEIGHT)
N_CELLS = N_CELLS_HORIZONTAL*N_CELLS_VERTICAL
